### ISSUE TITLE
[tracker] Update and expand Thoth architecture diagrams

### ISSUE THREAD

**Issue by codificat** [thoth-station/core#330]
**Is your feature request related to a problem? Please describe.**

Thoth is relatively complex, and it can be challenging to understand what are all the components and their interactions - both internal and external.

**High-level Goals**
list of high-level Acceptance Criteria/Goals (that is signed off by the team, and unchangeable)

As an individual who wants to understand how Thoth works, I would like to have a set of diagrams about Thoth components so that I can have a visual understanding of its architecture, integrations, and interaction points.

**Describe the solution you'd like**

A single diagram would not be enough here, because in order to be comprehensive it would have to be too complex, so multiple diagrams would be involved:

- a simple and high level overview diagram, showing external integration/interaction and only component names
- a diagram per component, i.e. a zoom in at each of the components of the overview

**Describe alternatives you've considered**

**Additional context**

There are some existing diagrams that can contribute to the whole story:

 - https://github.com/thoth-station/core/blob/master/docs/architecture.png could probably be updated as part of this effort
 - aicoe-ci pipelines https://github.com/AICoE/aicoe-ci#architecture
 - meteor deep dive diagram on aicoe-pipelines https://github.com/AICoE/meteor/issues/62
 - the Kebechet diagram at https://github.com/AICoE/data-driven-development/issues/24

**Acceptance Criteria**
checklist of detailed Acceptance Criteria (that might extend over the lifetime of the card)

- [ ] high level overview diagram
- [ ] component diagrams
  - [ ] AICoE pipelines: https://github.com/AICoE/aicoe-ci/issues/153
- [ ] links exist between diagrams (e.g. a single reference page)
- [ ] the various diagrams are visually consistent

**Comment by pacospace** [comment]
See also investigator docs: https://github.com/thoth-station/investigator

**Comment by codificat** [comment]
Also possibly related / could be part of this: https://github.com/thoth-station/core/issues/253

**Comment by pacospace** [comment]
> Also possibly related / could be part of this: #253

that issue might be closed, as we will consider sig-store, maybe it can be repurposed

**Comment by pacospace** [comment]
![Kebechet Schema-Kebechet advise (external trigger) (3)](https://user-images.githubusercontent.com/27498679/135264696-86be62d9-2a6c-4bca-a643-94b89cca4201.jpg)

**Comment by pacospace** [comment]
![Kebechet Schema-Kebechet advise (external trigger) (2)](https://user-images.githubusercontent.com/27498679/135264716-9a2d3f1b-d256-45b0-a46e-2cd3d131717c.jpg)

**Comment by pacospace** [comment]
![Kebechet Schema-Kebechet advise (internal trigger - package release) (1)](https://user-images.githubusercontent.com/27498679/135425783-b9e32889-6bad-463d-b7da-35adc4da4946.jpg)

**Comment by pacospace** [comment]
![Kebechet Schema-Kebechet advise (internal trigger - package release) (1)](https://user-images.githubusercontent.com/27498679/135425966-3126d237-7759-477b-beec-9d0413975170.jpg)

**Comment by pacospace** [comment]
![Kebechet Schema-Kebechet advise (internal trigger - package release)](https://user-images.githubusercontent.com/27498679/135426002-c453af47-e8f3-46ff-9a06-0671e5db74d4.jpg)

**Comment by pacospace** [comment]
new Thoth diagram https://app.diagrams.net/#G1XN1L8KLNtUNPIYL1QHEFcBv6lvcjN63M
![Thoth diagrams](https://user-images.githubusercontent.com/27498679/135625487-ebd2825d-da00-4d11-8115-0e3850178e3e.jpg)

**Comment by codificat** [comment]
Many thanks for these diagrams @pacospace, they look great!

Some comments about them:
- For the first two (internal and external triggers) I would probably just use the complete version of each. Maybe make the "main flow" black line slightly thicker, like you did with the last of the diagrams, for better clarity... but at that level of detail, we probably don't need a "more simple" version of each
- In the internal trigger diagram, I believe it would be better to have "gitub" be a small box towards the bottom, where the issue/pr arrow goes, similar to the thoth diagram, instead of taking all the left margin.

Beyond that, a more general comment about the approach here, in the context of this issue overall.

These are great diagrams to understand the details. However, we are still missing the higher level / general overview ones. In that sense, I wonder if it would not be better to start with these high-level ones: I believe it would help us achieve more consistency across the whole set.

In practical terms: this being a tracker issue for a "whole story" set of diagrams, should we split individual diagrams to their own separate issue/PR?

As a side note: I can't access the direct links to the diagram sources. Sharing the drawio file should work, but I'm not sure how practical that is.

**Comment by pacospace** [comment]
> Many thanks for these diagrams @pacospace, they look great!
> 
> Some comments about them:
> 
> * For the first two (internal and external triggers) I would probably just use the complete version of each. Maybe make the "main flow" black line slightly thicker, like you did with the last of the diagrams, for better clarity... but at that level of detail, we probably don't need a "more simple" version of each
> * In the internal trigger diagram, I believe it would be better to have "gitub" be a small box towards the bottom, where the issue/pr arrow goes, similar to the thoth diagram, instead of taking all the left margin.
> 
I ll adjust those thanks!
> Beyond that, a more general comment about the approach here, in the context of this issue overall.
> 
> These are great diagrams to understand the details. However, we are still missing the higher level / general overview ones. In that sense, I wonder if it would not be better to start with these high-level ones: I believe it would help us achieve more consistency across the whole set.

what kind of high level ones are we talking about? is the thoth diagram good for high level of all components we maintain?

> 
> In practical terms: this being a tracker issue for a "whole story" set of diagrams, should we split individual diagrams to their own separate issue/PR?
> 
Sounds good to open one for each diagram we want, thanks!

> As a side note: I can't access the direct links to the diagram sources. Sharing the drawio file should work, but I'm not sure how practical that is.

I ll check why the links do not work!

**Comment by goern** [comment]
ping?

**Comment by codificat** [comment]
/reopen
/lifecycle frozen

discussing this in today's SIG-UX meeting
