### ISSUE TITLE
[EPIC] Time-to-merge (TTM) bot as a service

### ISSUE THREAD

**Issue by Gkrumbach07** [thoth-station/core#425]
## Problem statement
As a user of a service, I want to know the estimate time a pull request will be resolved so I can more accurately track the resolution of my issue.

## High-level Goals
- [ ] A Github bot that comments the time to merge a PR
- [ ] A semi automated way to retrain the time to merge model

## Proposal description
Provide an installable GitHub bot that comments on a pull request an estimated [time to merge (TTM)](https://github.com/oindrillac/ocp-ci-analysis/tree/thoth-deployment/notebooks/time-to-merge-prediction) a pr. This bot should include a semi-automated way of retraining the bot's TTM model to a specific org or set of repos.

### Alternatives

- Use GitHub App to call the model service and post a comment to a PR. This has an added benefit of seeing the status of a prediction for each PR's acceptance criteria. However new features of the bot are limited in scope to what a GitHub App can do.
- Use an existing bot and add this feature as an addition to the bots feature set. Is a good option for a quick demo but as this bot could be its own service, it should be kept separate.

### Additional context

- TTM model trained on Thoth: https://github-pr-ttm-ds-ml-workflows-ws.apps.smaug.na.operate-first.cloud/predict%60
- [Example](https://gist.github.com/harshad16/158e642baf1415b5aa6068cd7d9f869b) on how to use the bot in Python using the MI tool

## Acceptance Criteria
- [x] https://github.com/thoth-station/core/issues/433
- [x] Decide if this can be its own service or should just be a part of Thoth
- [x] thoth-station/ttm-as-a-service#25
- [x] thoth-station/ttm-as-a-service#24
- [x] https://github.com/thoth-station/core/issues/432
- [x] thoth-station/ttm-as-a-service#23
- [ ] User can request a custom model trained on their org / set of repos
- [ ] document user-facing service maintenance interface
- [ ] publish a demo on our YT channel
- [ ] get feedback from packit team
- [ ] create ADR on GitHub App and the framework for its implementation

**Comment by tumido** [comment]
Take a look at https://github.com/operate-first/probot-template if it can be used here as well :slightly_smiling_face:

**Comment by Gkrumbach07** [comment]
Current resources

Namespace in Smaug cluster: https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/projects/ttm-as-a-service
namespace PR: https://github.com/operate-first/apps/pull/2290
TTM github repo: https://github.com/thoth-station/ttm-as-a-service
quay repo for TTM image: https://quay.io/repository/thoth-station/ttm-as-a-service

**Comment by oindrillac** [comment]
> User can request a custom model trained on their org / set of repos

hi @Gkrumbach07 we have a github action workflow setup to custom train the model https://github.com/redhat-et/time-to-merge-tool

Wanted to check if the inference action/bot is available anywhere to test or being used currently? 

Here https://github.com/redhat-et/time-to-merge-tool/issues/5 we are looking at an independent github action workflow which loads a model from S3 (does not point to a running service), gets the latest PR's data and sends a payload to the model and posts the model's output on a PR as a comment. Wanted to see if you were able to get this tool working on a new PR which points to the model service custom trained for Thoth.

**Comment by Gkrumbach07** [comment]
Hi @oindrillac. Our bot can be found [here](https://github.com/thoth-station/ttm-as-a-service), however it is not hosted at the moment as it only provides one model to use (the Thoth model). When installed on a repo or org, it will respond to PRs with a prediction using the model hosted on seldon.

I will take a look at the github action workflow and try to get it working.

**Comment by Gkrumbach07** [comment]
The action is running into issues. Any idea why? https://github.com/Gkrumbach07/time-to-merge-tool/actions/runs/3439990132/jobs/5737919078

**Comment by Gkrumbach07** [comment]
> Can you set the GITHUB_REPO (the repo that you are training this on), GITHUB_ORG (the org that the repo belongs to)

Github does not allow you to create secrets that begin in GITHUB. Is there something I am missing here. I provided those variables in the shell script.

**Comment by oindrillac** [comment]
my bad, the secret names are actually REPO & ORG. 
The correct variable names are listed under the manual trigger section here https://github.com/redhat-et/time-to-merge-tool#step-3
