### ISSUE TITLE
[TRACKER] Tech debt inventory (and possible solutions)

### ISSUE THREAD

**Issue by VannTen** [thoth-station/core#479]
We talked about handling our tech debt in last retrospective, so I'm going to start a list of items which in my opinion are in this category.
Feel free to add other !

Note: I'm heavily biased in favor of strong typing guarantees

- [ ] thoth-station/storages#2767
- [ ] thoth-station/prescriptions-refresh-job#206
- [ ] thoth-station/storages#2769
...

@goern @codificat @harshad16 @KPostOffice @Gkrumbach07
